### ISSUE TITLE
aws-sdk-sns dependency not found

### ISSUE THREAD

**Issue by dawn360** [mnk98/fastlane-plugin-sns_http_subscribe#1]
when adding the plugin I get the following error
`Error loading plugin 'fastlane-plugin-sns_http_subscribe': cannot load such file -- aws-sdk-sns`
Do I need to be adding this dep manually?

**Comment by mnk98** [comment]
Yes, need to install this dependency using gem

**Comment by dawn360** [comment]
is there a reason why we cannot add the dependency to fastlane-plugin-sns_http_subscribe.gemspec file? Thanks

**Comment by mnk98** [comment]
No reason, I'll try in next update
